nameOverride: worker

image:
  name: my-worker-example
  tag: latest

replicas: 1

resources:
  requests:
    cpu: 125m
    memory: 250Mi

environmentVariables:
  - FOO: bar
  - FOOBAR: foobar

probe:
  enabled: true
  livenessProbe:
    httpGet:
        port: 80
        httpHeaders:
        - name: probe
          value: liveness
        path: /healthy
    terminationGracePeriodSeconds: 2
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  
  readinessProbe:
    httpGet:
        port: 80
        httpHeaders:
        - name: probe
          value: readiness
        path: /healthy
    initialDelaySeconds: 1
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1

configMap:
  enabled: true
  propagateToEnv: true
  data: 
    DATA: DATA

hpa:
  enabled: false
  maxReplicas: 10
  minReplicas: 1
  cpu: 80

service:
  enabled: true
