nameOverride: worker

replicas: 2

configMap:
  enabled: true
  data:
    RABBITMQ_HOST: "rabbitmq.default"
    RABBITMQ_PORT: "5672"
    RABBITMQ_VHOST: "/"

hpa:
  enabled: true
  maxReplicas: 10
  minReplicas: 2
  cpu: 50

# Nginx test

image:
  name: nginx
  tag: latest

probe:
  enabled: true
  livenessProbe:
    httpGet:
        port: 80
        httpHeaders:
        - name: probe
          value: liveness
        path: /
    terminationGracePeriodSeconds: 2
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  
  readinessProbe:
    httpGet:
        port: 80
        httpHeaders:
        - name: probe
          value: readiness
        path: /
    initialDelaySeconds: 1
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1