networks:
  net: {}

services:
  rabbitmq:
    image: bitnami/rabbitmq:3.12.12-debian-11-r0
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: bitnami
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true
    ports:
      - "5672:5672"
    networks:
      - net
  event-ledger:
    image: event-ledger:1.0.1
    build:
      context: event-ledger/
    ports:
      - "3000:80"
    environment:
      - GIN_MODE=debug
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost/ping -qO - || exit 1"] # Using wget to avoid installing curl within the container
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 3s
    networks:
      - net
  worker:
    depends_on:
      - rabbitmq
    image: worker:1.0.0
    build:
      context: worker/
    environment:
      - GIN_MODE=debug
    networks:
      - net

