{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{- include "microservice.name" . | indent 1 }}-config
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}