{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{- include "microservice.name" . | indent 1 }}-hpa
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{- include "microservice.name" . | indent 1 }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.cpu }}
{{- end }}