apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker-svc
  name: worker-svc
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: worker-svc
  type: ClusterIP
