nameOverride: worker

probe:
  enabled: true
  livenessProbe:
    httpGet:
        port: 80
        path: /
    terminationGracePeriodSeconds: 2
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
    initialDelaySeconds: 1
  
  readinessProbe:
    httpGet:
        port: 80
        path: /
    initialDelaySeconds: 1
    periodSeconds: 3
    timeoutSeconds: 3
    failureThreshold: 2
    successThreshold: 1