apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: event-ledger-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/carlosgit2016/argocd-deployments.git
      revision: main
      files:
      - path: "clusters/config/alpha/config.yaml"
      - path: "clusters/config/beta/config.yaml"
      - path: "clusters/config/gamma/config.yaml"
  template:
    metadata:
      name: '{{.path.basename}}-event-ledger'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/carlosgit2016/argocd-deployments.git
          targetRevision: feat/event-ledger
          path: helm-charts/microservice
          helm:
            releaseName: event-ledger

            valueFiles:
            - $values/services/event-ledger/values.yaml
        - repoURL: https://github.com/carlosgit2016/argocd-deployments.git
          targetRevision: feat/event-ledger
          ref: values
      destination:
        server: '{{.cluster.address}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true