apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rabbitmq-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/carlosgit2016/argocd-deployments.git
      revision: main
      files:
      - path: "clusters/config/alpha/config.yaml"
  template:
    metadata:
      name: '{{.path.basename}}-rabbitmq'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/carlosgit2016/argocd-deployments.git
          targetRevision: main
          path: helm-charts/rabbitmq
          helm:
            releaseName: rabbitmq
            valueFiles:
            - $values/overrides/{{.path.basename}}/rabbitmq/values.yaml
        - repoURL: https://github.com/carlosgit2016/argocd-deployments.git
          targetRevision: main
          ref: values
      destination:
        server: '{{.cluster.address}}'
        namespace: rabbitmq
      syncPolicy:
        automated:
          prune: false
        syncOptions:
        - CreateNamespace=true