name: 'Golang services test, build and push'

on:
  pull_request:
    # paths:
    #   - "services/"
  push:
    paths:
      - "services/"
    branches:
      - "main"

permissions: 
  id-token: write
  contents: read

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/${{ matrix.services }}
    strategy:
      matrix:
        services: ['event-ledger', 'worker']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.19.1'
          cache-dependency-path: services/${{ matrix.services }}
      - name: Installing dependencies
        run: go install
      - name: "Testing"
        run: go test ./...
        if: ${{ matrix.services == 'worker' }}
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: ['event-ledger', 'worker']
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::169740125934:role/gh-actions-role
          role-session-name: awsrole
          aws-region: us-east-1

      - name: Get commit short sha
        if: github.ref_name != 'main'
        id: sha
        run: echo "short=$(git rev-parse --short origin/${{ github.head_ref }})" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ecr login
        run: aws ecr get-login-password | docker login --username AWS --password-stdin 169740125934.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: services/${{ matrix.services }}
          push: true
          tags: 169740125934.dkr.ecr.us-east-1.amazonaws.com/${{ matrix.services }}:${{ github.ref_name == 'main' && 'latest' || steps.sha.outputs.short }}