name: 'Golang services test, build and push'

on:
  pull_request:
    paths:
      - "services/"
  push:
    paths:
      - "services/"
    branches:
      - "main"

permissions: 
  id-token: write
  contents: read

jobs:
  golang-build-and-test:
    uses: ./.github/workflows/test-and-build.yml
    strategy:
      matrix:
        services: ['event-ledger', 'worker', 'aws-token-refresher']
    with:
      golang: ${{ matrix.services == 'event-ledger' }}
      working-directory: services/${{ matrix.services }}
      context: services/${{ matrix.services }}
      image: ${{ matrix.services }}
      use-sha: ${{ github.ref_name != 'main' }}