name: 'Reusable workflow for test and build golang applications'

on:
  workflow_call: 
    inputs:
        golang:
            required: false
            default: true
            type: boolean

        unit-test:
            required: false
            default: true
            type: boolean

        working-directory:
            required: true
            type: string

        context:
            required: true
            type: string

        image:
            required: true
            type: string

        tag:
            required: false
            default: latest
            type: string
    
        use-sha:
            required: false
            default: false
            type: boolean

jobs:
  golang:
    if: github.event_name == 'pull_request' && inputs.golang
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.19.1'
          cache-dependency-path: ${{ inputs.working-directory }}
      - name: Installing dependencies
        run: go install
      - name: "Testing"
        run: go test ./...
        if: inputs.unit-test 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::169740125934:role/gh-actions-role
          role-session-name: awsrole
          aws-region: us-east-1

      - name: Get commit short sha
        if: inputs.use-sha
        id: sha
        run: echo "short=$(git rev-parse --short origin/${{ github.head_ref }})" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ecr login
        run: aws ecr get-login-password | docker login --username AWS --password-stdin 169740125934.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          push: true
          tags: "169740125934.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.image }}:${{ inputs.use-sha && steps.sha.outputs.short || inputs.tag }}"